name: mobile
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  sqflite: ^1.1.6+1
  path_provider: ^1.1.0
  flutter_bloc: ^0.18.3
  quiver: '>=2.0.0 <3.0.0'
  intl: ^0.15.8
  smooth_star_rating: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true